spring.application.name=MyFinance.com
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/finance_tracker
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=my-super-long-secret-key-which-is-32chars+
app.jwt.expiration-ms=86400000000

# Fix Swagger path patterns
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# RE-ENABLE Swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html